# Django SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'


# AWSのS3バケット名と、アクセスキーを設定必要
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_ACCESS_KEY_ID = 'AKIAXXXXXXXXXXXXXXXXX'
AWS_SECRET_ACCESS_KEY = 'ECn6iXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
AWS_STORAGE_BUCKET_NAME = 'chaptan-XXXXX'


# メール通知設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'XXXXXXXXXXX@gmail.com'
EMAIL_HOST_PASSWORD = 'aXXXXXXXXXXXXXX'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = 'XXXXXXXXXXX@gmail.com'
