# Generated by Django 3.2.23 on 2023-12-23 02:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_text',
            field=mdeditor.fields.MDTextField(default='## 要約生成中'),
        ),
    ]
