# Generated by Django 3.2.23 on 2023-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0002_alter_summary_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='storage/videos/'),
        ),
    ]
