# Generated by Django 3.2.23 on 2023-11-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0003_chapter_video_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='video_path',
            new_name='video_file_path',
        ),
    ]
