# Generated by Django 3.2.23 on 2023-11-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0004_rename_video_path_chapter_video_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='動画圧縮中', max_length=50),
        ),
    ]
