# Generated by Django 3.2.23 on 2023-11-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0005_alter_chapter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='文字起こし中', max_length=50),
        ),
    ]
