# Generated by Django 3.2.23 on 2023-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0006_alter_chapter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='処理順番待ち', max_length=50),
        ),
    ]
