# Generated by Django 3.2.23 on 2023-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0007_alter_chapter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video_title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
