# Generated by Django 3.2.23 on 2023-12-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0008_alter_chapter_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(default='a', upload_to='storage/videos'),
            preserve_default=False,
        ),
    ]
