# Generated by Django 3.2.23 on 2023-12-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0009_auto_20231203_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(upload_to='storage/videos/<django.db.models.fields.CharField>'),
        ),
    ]
