# Generated by Django 3.2.23 on 2023-12-05 13:51

import chapter_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0010_alter_chapter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='transcription_file',
            field=models.FileField(null=True, upload_to='storage/transcriptions/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='video_file',
            field=models.FileField(upload_to=chapter_app.models.video_directory_path),
        ),
    ]
