# Generated by Django 3.2.23 on 2023-12-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0011_auto_20231205_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='transcription_file',
            new_name='transcription_path',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='video_file',
            new_name='video_path',
        ),
    ]
