# Generated by Django 3.2.23 on 2023-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0012_auto_20231207_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='transcription_path',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
