# Generated by Django 3.2.23 on 2023-12-19 14:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0013_alter_chapter_transcription_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='summary_text',
            field=mdeditor.fields.MDTextField(default=2),
            preserve_default=False,
        ),
    ]
