# Generated by Django 3.2.23 on 2023-12-20 14:23

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_app', '0014_chapter_summary_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chapter_app.chapter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_text', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='summary_text',
        ),
    ]
