# Generated by Django 3.2.23 on 2023-12-22 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chapter_app', '0015_auto_20231220_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='auth.group'),
        ),
    ]
